name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Install pnpm
        run: npm install -g pnpm
      # Install pnpm
      - name: Install Dependencies
        run: pnpm install
      # Run build:lib
      - name: Build Library
        run: pnpm run build:lib
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  Version-Up:
    needs: ["Deploy-Production"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "github-actions@example.com"
      - run: git config --global user.name "GitHub Actions"
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      # # Install pnpm globally
      # - name: Install PNPM
      #   run: npm install -g pnpm
      # # Install pnpm
      # - name: Install Dependencies
      #   run: pnpm install
      # # Run build:lib
      # - name: Build Library
      #   run: pnpm run build:lib

      - name: Set new patch version
        if: "!contains(github.event.head_commit.message, '+m')"
        run: "npm version patch -m 'ver: %s'"

      - name: Set new minor version
        if: "contains(github.event.head_commit.message, '+minor')"
        run: "npm version minor -m 'ver: %s'"

      - name: Set new major version
        if: "contains(github.event.head_commit.message, '+major')"
        run: "npm version major -m 'ver: %s'"

      - name: push branch
        run: git push
      #!이거 뭔데 오래걸려 갑자기
      #!- uses: actions/upload-artifact@v2
      #!   with:
      #!     name: src
      #!     path: ./

  NPM-Publish:
    needs: ["Version-Up"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      # Install pnpm globally
      - name: Install PNPM
        run: npm install -g pnpm
      # Install Dependencies
      - name: Install Dependencies
        run: pnpm install
      # Run build:lib
      - name: Build Library
        run: pnpm run build:lib
      - name: Pull branch
        run: git pull
      # Then, Publish to NPM
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v2.2.1
        id: junyeol-components
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./package.json"
      - name: Set color based on outcome
        if: always()
        id: set-color
        run: |
          if [ "${{ steps.junyeol-components.outcome }}" == "success" ]; then
            echo "slack_color=#36a64f" >> $GITHUB_ENV
          else
            echo "slack_color=#FF0000" >> $GITHUB_ENV
          fi
      - name: Slack message
        if: always()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "attachments": [{
                "pretext": "A new repository has been created",
                "color": "${{ env.slack_color }}",
                "fields": [
                    {
                        "title": "NPM publish ${{ steps.junyeol-components.outcome }}",
                        "value": "npm url: https://www.npmjs.com/package/junyeol-components",
                        "short": true
                        }
                    ]
                  }
                ]
            }

  tag:
    needs: NPM-Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull branch
        run: git pull

      - name: Get version
        id: get-version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

      - name: Create release & tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: ${{ steps.get-version.outputs.version }}
